### ISSUE TITLE
Error on multi-company instances

### ISSUE THREAD

**Issue by flexy2ky** [dvdl16/erpnext_customer_statements_sender#1]
Awesome Effort!!!! However, there's a small bug. It doesn't seem to take into account multi-company instances so it throws errors when you try to preview a statement.

Also tied to this, can you include a company filter so customer statements are fetched based on company?

**Comment by dvdl16** [comment]
Hi @flexy2ky, do you mind posting a screenshot/traceback of the errors? Sorry I haven't added any unit testing so this may be trial and error for now

**Comment by dvdl16** [comment]
@flexy2ky I think I've duplicated the issue, let me have a look

**Comment by dvdl16** [comment]
@flexy2ky Please check if it's fine now. To update:
Run `bench update` (this will update all installed apps)
or
1. `cd frappe-bench/apps/erpnext_customer_statements_sender`
2. `git pull`
3. `cd ../..`
4. `bench migrate`

**Comment by flexy2ky** [comment]
issue fixed with latest pull! Thanks for the fix!!! This will be an awesome addition to the core if it can be added.
